# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

# no PR builds on this file
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g webpack webpack-cli --save-dev
      npm install
    displayName: 'NPM install'

  - script: |
      npx webpack --config webpack.config.js
    displayName: 'NPX Webpack'

  - script: |
      npm run test
    displayName: 'Unit test'

  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '$(System.DefaultWorkingDirectory)/unit-test-report.xml'
      testRunTitle: Unit test results
      failTaskOnFailedTests: true
    condition: succeededOrFailed()

  - script: |
      npm run test:integration
    displayName: 'Integration test'

  - task: PublishTestResults@2
    displayName: Publish integration test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '$(System.DefaultWorkingDirectory)/integration-test-report.xml'
      testRunTitle: Integration test results
      failTaskOnFailedTests: true
    condition: succeededOrFailed()